# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: '1 */2 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev   libsdl1.2-dev libsmpeg-dev python-numpy subversion libportmidi-dev ffmpeg libswscale-dev libavformat-dev libavcodec-dev
        #sudo apt-get build-dep python-pygame
        #sudo apt-get install libsdl1.2-dev portaudio19-dev
        python -m pip install --upgrade pip
        #sudo apt-get install libsdl-image1.2-dev libsdl2-dev libsdl-ttf2.0-dev
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build the Arb and Create the file
      run: |
         python main_webscraper.py -j9
         git config --global user.name "tiamica"
         git config --global user.email "games@tiamica.com"
         git add results.html 
         git commit -am"Updated to latest results"
         git checkout -b release
         git merge master
         git push -f origin release
